// PROJECT TYPES
// narrative, commercial, music-videos, documentary

const projectsData = [
    {
    id: "mirage",
    title: "Mirage",
    category: "narrative",
    featured: true,
    thumbnail: "thumbnails/mirage.mp4",
    videoUrl: "https://vimeo.com/675229805",
    director: "Dustin Tan",
    director_of_photography: "Jake Wolfert",
    awards: "Featured on Beyond The Short and Film Shortage\nOfficial Selection Maryland Film Festival 2022\nOfficial Selection Palm Springs Film Festival 2022",
    },
    {
    id: "betweenfriends-lonely",
    title: "Between Friends - Lonely",
    category: "music-videos",
    featured: true,
    thumbnail: "thumbnails/lonely.mp4",
    videoUrl: "https://www.youtube.com/watch?v=BP8G0JQaMJ0",
    director: "Kevin Clark",
    director_of_photography: "Jake Wolfert",
    awards: "Shortlisted UK music-videos Awards 2021",
    },
    {
    id: "gapkids-justdance",
    title: "Gap Kids - Just Dance",
    category: "commercial",
    featured: true,
    thumbnail: "thumbnails/gapkids.mp4",
    videoUrl: "https://vimeo.com/997553548",
    director: "Duncan Wolfe",
    director_of_photography: "Jake Wolfert",
    starring: "Jon Heder and Efren Ramirez"
    },
    {
    id: "king-of-the-hill-pt-II",
    title: "King of The Hill Part II",
    category: "narrative",
    featured: true,
    thumbnail: "thumbnails/kothpii.mp4",
    videoUrl: "https://vimeo.com/345993036",
    director: "Jake Wolfert",
    director_of_photography: "Adrian Nieto",
    awards: "Official Selection Bizarroland Film Festival 2020\nOfficial Selection Vinilonga International Short Film Festival 2019\nOfficial Selection Cine Underground Film Festival 2019\nOffical Selection Terror en el MAAC Vol. IV 2019\nOfficial Selection Film Maudit 2.0 Film Festival 2019\nOfficial Selection Cinematic Panic Film Festival 2019\nOfficial Selection What The Fest Film Festival 2019\nOfficial Selection Stuff MX Film Festival 2019",
    },
    {
    id: "arcteryx-the-true-test",
    title: "Arc'teryx - The True Test",
    category: "commercial",
    featured: true,
    thumbnail: "thumbnails/arcteryx.mp4",
    videoUrl: "https://vimeo.com/738129803",
    director: "Ezra Ewen",
    director_of_photography: "Jake Wolfert",
    awards: "Vimeo Staff Pick",
    },
    {
    id: "jawny-best-thing",
    title: "Jawny - Best Thing",
    category: "music-videos",
    featured: false,
    thumbnail: "thumbnails/bestthing.mp4",
    videoUrl: "https://www.youtube.com/watch?v=e3Ez2DOC7aM",
    director: "Spencer Ford",
    director_of_photography: "Jake Wolfert",
    },
    {
        id: "vanillaroma-buzzkill-bummer",
    title: "Vanillaroma - Buzzkill Bummer",
    category: "music-videos",
    featured: false,
    thumbnail: "thumbnails/buzzkillbummer.mp4",
    videoUrl: "https://www.youtube.com/watch?v=K9tb1znUXWQ",
    director: "Spencer Ford",
    director_of_photography: "Jake Wolfert",
    },
    {
        id: "between-friends-orange-juice",
    title: "Between Friends - Orange Juice",
    category: "music-videos",
    featured: false,
    thumbnail: "thumbnails/orangejuice.mp4",
    videoUrl: "https://www.youtube.com/watch?v=BA5PG2WMzYY",
    director: "Kevin Clark",
    director_of_photography: "Jake Wolfert",
    },
    {
        id: "jawny-take-it-back",
    title: "Jawny - Take It Back",
    category: "music-videos",
    featured: false,
    thumbnail: "thumbnails/takeitback.mp4",
    videoUrl: "https://www.youtube.com/watch?v=WgOap8nTjn0",
    director: "Spencer Ford",
    director_of_photography: "Jake Wolfert",
    },
    {
    id: "wovvoka-gang",
    title: "Wovvoka - GANG!!!",
    category: "music-videos",
    featured: false,
    thumbnail: "thumbnails/gang.mp4",
    videoUrl: "https://www.youtube.com/watch?v=8JAfMHg4Uz4",
    director: "Spencer Ford",
    director_of_photography: "Jake Wolfert",
    },
    {
    id: "cold-war-kids-what-you-say",
    title: "Cold War Kids - What You Say",
    category: "music-videos",
    featured: false,
    thumbnail: "thumbnails/whatyousay.mp4",
    videoUrl: "https://www.youtube.com/watch?v=60Rx9_K_Pqw",
    director: "Jakob Longcob",
    director_of_photography: "Jake Wolfert",
    },
    {id: "juggler-gave-you-my-all",
    title: "Juggler - Gave You My All",
    category: "music-videos",
    featured: false,
    thumbnail: "thumbnails/juggler.mp4",
    videoUrl: "coming soon",
    director: "Maleah Goldberg",
    director_of_photography: "Jake Wolfert",
},
{
    id: "marsfade-do-u-know-what-i-mean",
    title: "Marsfade - Do U Know What I Mean",
    category: "music-videos",
    featured: false,
    thumbnail: "thumbnails/marsfade.mp4",
    videoUrl: "https://www.youtube.com/watch?v=DrkV8diyk8Y",
    director: "Dustin Tan",
    director_of_photography: "Jake Wolfert",
},
{
    id: "waveform-tell-you",
    title: "waveform* - Tell You",
    category: "music-videos",
    featured: false,
    thumbnail: "thumbnails/tellyou.mp4",
    videoUrl: "https://vimeo.com/user22147635",
    director: "Dustin Tan",
    director_of_photography: "Jake Wolfert",
},
{
    id: "jawny-trigger-of-love",
    title: "Jawny - Trigger of Love",
    category: "music-videos",
    featured: false,
    thumbnail: "thumbnails/triggeroflove.mp4",
    videoUrl: "https://www.youtube.com/watch?v=n_83u9eEgHk",
    director: "Spencer Ford",
    director_of_photography: "Jake Wolfert",
},
{
    id: "brockhampton-no-halo",
    title: "Brockhampton - No Halo",
    category: "music-videos",
    featured: false,
    thumbnail: "thumbnails/nohalo.mp4",
    videoUrl: "https://www.youtube.com/watch?v=5PHqk_7kIWk",
    director: "Spencer Ford",
    director_of_photography: "Jake Wolfert",
},
{
    id: "chromeo-new-girl",
    title: "Chromeo - (I Don't Need A) New Girl",
    category: "music-videos",
    featured: false,
    thumbnail: "thumbnails/chromeo.mp4",
    videoUrl: "https://www.youtube.com/watch?v=kg8pPuLURaE",
    director: "Spencer Ford",
    director_of_photography: "Jake Wolfert",
},
{
    id: "worthitpurchase-gladly-fading",
    title: "Worthitpurchase - Gladly Fading",
    category: "music-videos",
    featured: false,
    thumbnail: "thumbnails/gladlyfading.mp4",
    videoUrl: "https://www.youtube.com/watch?v=mHq5R2xkQIM",
    director: "Jakob Longcob & Jake Wolfert",
    director_of_photography: "Jake Wolfert",
},
{
    id: "wallows-pictures-of-girls",
    title: "Wallows - Pictures of Girls",
    category: "music-videos",
    featured: false,
    thumbnail: "thumbnails/wallows.mp4",
    videoUrl: "https://www.youtube.com/watch?v=keD0IJP4Dtw",
    director: "Shelly",
    director_of_photography: "Jake Wolfert",
},
{
    id: "photographic-memory-care-too",
    title: "Photographic Memory - Care Too",
    category: "music-videos",
    featured: false,
    thumbnail: "thumbnails/caretoo.mp4",
    videoUrl: "https://www.youtube.com/watch?v=8oxsxiOcVyw",
    director: "Jakob Longcob & Jake Wolfert",
    director_of_photography: "Jake Wolfert",
},
{
    id: "vanillaroma-pickpocket",
    title: "Vanillaroma - Pickpocket",
    category: "music-videos",
    featured: false,
    thumbnail: "thumbnails/pickpocket.mp4",
    videoUrl: "https://www.youtube.com/watch?v=8oxsxiOcVyw",
    director: "Jakob Longcob & Jake Wolfert",
    director_of_photography: "Jake Wolfert",
},
{
    id: "actual-inc-purple-sunset-over-lake-2",
    title: "Actual Inc. - Purple Sunset Over Lake 2",
    category: "music-videos",
    featured: false,
    thumbnail: "thumbnails/purplesunset.mp4",
    videoUrl: "https://www.youtube.com/watch?v=lD7rSxPncs4",
    created_by: "Jake Wolfert",
},
{
    id: "actual-inc-sunscreen",
    title: "Actual Inc. - Sunscreen",
    category: "music-videos",
    featured: false,
    thumbnail: "thumbnails/sunscreen.mp4",
    videoUrl: "https://www.youtube.com/watch?v=VBaWtOHPTZw",
    created_by: "Jake Wolfert",
},
{
    id: "spill-tab-fetish",
    title: "Spill Tab - Fetish",
    category: "music-videos",
    featured: false,
    thumbnail: "thumbnails/fetish.mp4",
    videoUrl: "https://www.youtube.com/watch?v=j4Gy3JNOVnQ",
    director: "Spencer Ford",
    director_of_photography: "Jake Wolfert",
    
},
{
    id: "bia-boilerroom-valentino",
    title: "Skate by Bia - In Partnership with Boiler Room",
    category: "commercial",
    featured: false,
    thumbnail: "thumbnails/bia.mp4",
    videoUrl: "https://www.youtube.com/watch?v=N4vBftTUWDo",
    director: "Kevin Clark",
    director_of_photography: "Jake Wolfert",
},
{
    id: "figs-oasis-pink-sands",
    title: "Figs - Oasis + Pink Sands",
    category: "commercial",
    featured: false,
    thumbnail: "thumbnails/figs.mp4",
    videoUrl: "https://vimeo.com/961942688",
    director: "Dustin Tan",
    director_of_photography: "Jake Wolfert",
},
{
    id: "little-fish",
    title: "Little Fish",
    category: "commercial",
    featured: false,
    thumbnail: "thumbnails/littlefish.mp4",
    videoUrl: "https://vimeo.com/569537808",
    director: "Ezra Ewen",
    director_of_photography: "Jake Wolfert",
},
{
    id: "avenue-43",
    title: "Avenue 43",
    category: "documentary",
    featured: false,
    thumbnail: "thumbnails/avenue43.mp4",
    videoUrl: "https://www.youtube.com/watch?v=cX5MyNz7wfg",
    created_by: "Jake Wolfert",
},
{
    id: "slauson_&_labrea",
    title: "Slauson & LaBrea",
    category: "documentary",
    featured: false,
    thumbnail: "thumbnails/slausonandlabrea.mp4",
    videoUrl: "coming soon",
    created_by: "Jake Wolfert",
},
{
    id: "city_of_los_angeles_property",
    title: "City of Los Angeles Property",
    category: "documentary",
    featured: false,
    thumbnail: "thumbnails/cityofla.mp4",
    videoUrl: "https://www.youtube.com/watch?v=8sQwvkvdBAI",
    created_by: "Jake Wolfert",
},
{
    id: "for_all_purposes_throughout_the_universe_in_perpetuity",
    title: "For All Purposes Throughout the Universe in Perpetuity",
    category: "documentary",
    featured: false,
    thumbnail: "thumbnails/forallpurposes.mp4",
    videoUrl: "https://www.youtube.com/watch?v=ojlgkXJhVf4",
    created_by: "Jake Wolfert",
},
{
    id: "figueroa_street_tunnels",
    title: "Figueroa Street Tunnels",
    category: "documentary",
    featured: false,
    thumbnail: "thumbnails/figueroastreettunnels.mp4",
    videoUrl: "https://www.youtube.com/watch?v=W6rZIhd7wMY",
    created_by: "Jake Wolfert",
},
{
    id: "angelus_rosedale_cemetery",
    title: "Angelus Rosedale Cemetery",
    category: "documentary",
    featured: false,
    thumbnail: "thumbnails/angelusrosedalecemetery.mp4",
    videoUrl: "https://www.youtube.com/watch?v=-eR6G0TUCYM",
    created_by: "Jake Wolfert",
},
{
    id: "ladder",
    title: "Ladder walking down steepest street in California",
    category: "documentary",
    featured: false,
    thumbnail: "thumbnails/ladder.mp4",
    videoUrl: "https://www.youtube.com/watch?v=__PgRC3JYWc",
    created_by: "Jake Wolfert",
},
{
    id: "dented_road",
    title: "Dented Road",
    category: "documentary",
    featured: false,
    thumbnail: "thumbnails/dentedroad.mp4",
    videoUrl: "https://www.youtube.com/watch?v=fTOOyJDMX50",
    created_by: "Jake Wolfert",
},
{
    id: "kron",
    title: "KRON",
    category: "documentary",
    featured: false,
    thumbnail: "thumbnails/kron.mp4",
    videoUrl: "https://vimeo.com/316366180",
    created_by: "Jake Wolfert",
    awards: "Official Selection Darkroom Film Festival 2019",
},
{
    id: "face-in-the-sky",
    title: "Face in the Sky",
    category: "narrative",
    featured: false,
    thumbnail: "thumbnails/faceinthesky.mp4",
    videoUrl: "coming soon",
    director: "Kevin Clark",
    writer: "Robby Che",
    director_of_photography: "Jake Wolfert",
}   
    
];

// If you're using ES6 modules
// export default projectsData;

// If you're not using ES6 modules, uncomment the line below
window.projectsData = projectsData;
